import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from   "@/components/Navbar";

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] }); // ✅


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-6xl mx-auto h-[100vh]">
          <Navbar />
       
        {children}
         </div>
      </body>
    </html>
    </ClerkProvider>
    
  );
}
